version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin https://public.ecr.aws/r0c3j2a2/vuejsweb/wangzichenglong
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t https://public.ecr.aws/r0c3j2a2/vuejsweb/wangzichenglong:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push https://public.ecr.aws/r0c3j2a2/vuejsweb/wangzichenglong:latest
