version: 0.2

phases:
  pre_build:
    commands:
      - echo "Skipping login as we are using a public ECR repository"      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  discard-paths: yes

  # Needed by ECS CodePipeline to determine the image to deploy
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'
